import { useState, useMemo, useEffect, useCallback } from 'react';
import { Search, Eye, Printer, Download, Receipt, Loader2, Calendar, Trash2, CheckCircle2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { ZReport } from '@/types';
import { Modal } from '@/components/Modal';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { ZReportDocument } from '@/components/ZReportModal';
import { formatETB, formatDate, formatDateTime } from '@/lib/utils';

export function ZReportsHistoryTab() {
  const [reports, setReports] = useState<ZReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [dateFilter, setDateFilter] = useState('');
  const [viewing, setViewing] = useState<ZReport | null>(null);
  const [clearOpen, setClearOpen] = useState(false);
  const [clearing, setClearing] = useState(false);
  const [toast, setToast] = useState(false);

  const loadReports = useCallback(async () => {
    const { data } = await supabase
      .from('z_reports')
      .select('*')
      .order('generated_at', { ascending: false });
    setReports(data ?? []);
    setLoading(false);
  }, []);

  useEffect(() => {
    loadReports();
  }, [loadReports]);

  const filtered = useMemo(() => {
    return reports.filter((r) => {
      if (dateFilter && r.business_date !== dateFilter) return false;
      if (search.trim()) {
        const q = search.toLowerCase();
        return (
          r.generated_by_name.toLowerCase().includes(q) ||
          r.report_number.toString().includes(q) ||
          r.business_date.includes(q)
        );
      }
      return true;
    });
  }, [reports, search, dateFilter]);

  function handlePrint() {
    window.print();
  }

  function handleDownload(report: ZReport) {
    const content = generateReportText(report);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `z-report-${report.report_number}-${report.business_date}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-16">
        <Loader2 size={24} className="animate-spin text-gray-400" />
      </div>
    );
  }

  return (
    <div>
      <div className="flex flex-col sm:flex-row gap-3 mb-4">
        <div className="relative flex-1">
          <Search size={18} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search by report #, date, or generator..."
            className="input pl-11"
          />
        </div>
        <div className="relative">
          <Calendar size={18} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
          <input
            type="date"
            value={dateFilter}
            onChange={(e) => setDateFilter(e.target.value)}
            className="input pl-11 sm:w-44"
          />
        </div>
        {dateFilter && (
          <button onClick={() => setDateFilter('')} className="btn-secondary shrink-0">
            Clear Date
          </button>
        )}
        {reports.length > 0 && (
          <button
            onClick={() => setClearOpen(true)}
            className="btn-secondary text-red-600 hover:bg-red-50 border-red-200 shrink-0"
          >
            <Trash2 size={16} /> Clear History
          </button>
        )}
      </div>

      {filtered.length === 0 ? (
        <div className="text-center py-12">
          <Receipt size={36} className="mx-auto text-gray-300 mb-2" />
          <p className="text-gray-400 text-sm">No Z Reports found.</p>
        </div>
      ) : (
        <div className="space-y-2">
          {filtered.map((report) => (
            <div key={report.id} className="card p-4 flex items-center gap-3">
              <div className="w-11 h-11 rounded-xl bg-brand-50 text-brand-600 flex items-center justify-center shrink-0">
                <Receipt size={20} />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-0.5">
                  <span className="font-semibold text-sm text-gray-900">Report #{report.report_number}</span>
                  <span className="badge bg-brand-50 text-brand-700 border-brand-100">{formatDate(report.business_date)}</span>
                </div>
                <p className="text-xs text-gray-400">
                  {report.total_orders} orders · {report.completed_orders} completed · {report.cancelled_orders} cancelled
                </p>
                <p className="text-xs text-gray-400">Generated by {report.generated_by_name} · {formatDateTime(report.generated_at)}</p>
              </div>
              <div className="text-right shrink-0">
                <p className="text-xs text-gray-400">Revenue</p>
                <p className="font-bold text-sm text-green-600">{formatETB(report.total_revenue)}</p>
              </div>
              <div className="flex gap-1 shrink-0">
                <button onClick={() => setViewing(report)} className="p-2 rounded-lg hover:bg-gray-100 text-gray-500" title="View">
                  <Eye size={16} />
                </button>
                <button onClick={() => handleDownload(report)} className="p-2 rounded-lg hover:bg-gray-100 text-gray-500" title="Download">
                  <Download size={16} />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {viewing && (
        <Modal open onClose={() => setViewing(null)} title={`Z Report #${viewing.report_number}`} size="lg">
          <div className="print-area">
            <ZReportDocument report={viewing} />
          </div>
          <div className="flex gap-3 mt-5 no-print">
            <button onClick={handlePrint} className="btn-secondary flex-1">
              <Printer size={16} /> Print
            </button>
            <button onClick={() => handleDownload(viewing)} className="btn-secondary flex-1">
              <Download size={16} /> Download
            </button>
            <button onClick={() => setViewing(null)} className="btn-primary flex-1">
              Close
            </button>
          </div>
        </Modal>
      )}

      <ConfirmDialog
        open={clearOpen}
        title="Clear Z Report History"
        destructive
        confirmLabel={clearing ? 'Clearing...' : 'Confirm Clear'}
        message={
          <>
            Are you sure you want to clear all past Z Report history?
            <br />
            This action cannot be undone.
          </>
        }
        onConfirm={async () => {
          setClearing(true);
          const { error } = await supabase.from('z_reports').delete().neq('id', '00000000-0000-0000-0000-000000000000');
          setClearing(false);
          if (error) return;
          setReports([]);
          setClearOpen(false);
          setToast(true);
          setTimeout(() => setToast(false), 3500);
        }}
        onClose={() => setClearOpen(false)}
      />

      {toast && (
        <div className="fixed top-4 right-4 z-50 animate-in fade-in slide-in-from-top-2 duration-300">
          <div className="flex items-center gap-3 bg-white border border-green-200 shadow-lg rounded-xl px-4 py-3 max-w-sm">
            <div className="w-9 h-9 rounded-full bg-green-100 text-green-600 flex items-center justify-center shrink-0">
              <CheckCircle2 size={18} />
            </div>
            <p className="font-semibold text-sm text-gray-900">Z Report history cleared successfully</p>
          </div>
        </div>
      )}
    </div>
  );
}

function generateReportText(report: ZReport): string {
  const lines: string[] = [];
  lines.push('========================================');
  lines.push('       MARCILAS RESTAURANT');
  lines.push('       Dire Dawa, Ethiopia');
  lines.push('       Z REPORT — Daily Closing');
  lines.push('========================================');
  lines.push('');
  lines.push(`Report #:     ${report.report_number}`);
  lines.push(`Business Date: ${report.business_date}`);
  lines.push(`Generated At: ${formatDateTime(report.generated_at)}`);
  lines.push(`Generated By: ${report.generated_by_name}`);
  lines.push('');
  lines.push('--- SUMMARY ---');
  lines.push(`Total Orders:     ${report.total_orders}`);
  lines.push(`Completed Orders: ${report.completed_orders}`);
  lines.push(`Cancelled Orders: ${report.cancelled_orders}`);
  lines.push(`Total Discounts:  ${formatETB(report.total_discounts)}`);
  lines.push(`Total Revenue:    ${formatETB(report.total_revenue)}`);
  lines.push('');
  const orders = report.order_snapshot ?? [];
  if (orders.length > 0) {
    lines.push('--- ORDERS ---');
    orders.forEach((o, i) => {
      lines.push(`${i + 1}. ${o.customer_name} | ${o.status} | ${o.payment_status} | ${formatETB(o.total)}`);
    });
    lines.push('');
  }
  lines.push('========================================');
  lines.push('Orders are archived and not deleted.');
  lines.push('========================================');
  return lines.join('\n');
}
